### ISSUE TITLE
lf_command_override broken(?)

### ISSUE THREAD

**Issue by BachoSeven** [ptzz/lf.vim#5] opened 2020-04-20 10:55 UTC
Hi, I've been using this for a while so thank you!

With the latest build of lf, the configuration `let g:lf_command_override = 'lf -command "set hidden"'` is not respected, while it used to.

If I try several times (\f q \f q \f q) it shows hidden files like 40% of the time; which is weird
What I think happens is `set hidden` is actualy on, because even when .files do not show, using my mapping for `set hidden!` in the lf buffer does nothing on the first press, and then shows hidden files on the second press, which means it was set in the first place. Indeed, on `reload` it shows hidden files.

Edit: I tried running `lf -command "set hidden"` outside of vim and I have the same issue, so I guess this is related to lf. I will try debugging it and open an issue over there in case

**Comment by ptzz** [comment] 2020-04-20 12:02
Hi, thanks for reporting. I haven't used that feature myself but just tested and it seems to work fine on my side. But I'm probably not on latest latest lf binary.

Since you have confirmed the issue with the lf binary I'm closing this for now. Let's reopen if it turns out to be an issue with the plugin.

**Closed as completed by ptzz** 2020-04-20 12:02 UTC
