### ISSUE TITLE
Issue with parsing name of directory which contains a double dollar sign

### ISSUE THREAD

**Issue by BachoSeven** [ptzz/lf.vim#21] opened 2021-02-11 20:32 UTC
![image](https://user-images.githubusercontent.com/55460785/107695112-6fc29880-6cb0-11eb-93df-232a62ba148f.png)

The actual name of the directory is `$$b`.
To reproduce, do `mkdir '\$\$b' && nvim "$$b/file"` and then open `:Lf`.

**Comment by ptzz** [comment] 2021-02-12 08:46
Hmm `mkdir -p '$$b' && nvim '$$b/file'` works for me.

With `mkdir '\$\$b'` I get a directory actually called `\$\$b`.

And double quotes `"$$b/file"` implies variable expansion, no? This is what I see on Macos bash:

```
~/tmp$ unset b
~/tmp$ echo "$$b"
4971b
~/tmp$ echo '$$b'
$$b
```

**Comment by BachoSeven** [comment] 2021-02-12 11:56
Sorry for the confusion around the command I provided, probably has to do with my shell setup. However, from a clean (`zsh --no-rcs`) shell, `mkdir '$$' && cd '$$' && touch file && nvim file`, and then `:Lf`, gives 
``` vim
Error detected while processing function OpenLfIn[4]..floaterm#run[7]..floaterm#new[7]..float
erm#wrapper#lf#:
line   14:
E344: Can't find directory "/home/fra/841133" in cdpath
E472: Command failed
Error detected while processing function OpenLfIn[4]..floaterm#run[7]..floaterm#new:
line    7:
E714: List required
```

**Comment by ptzz** [comment] 2021-02-12 13:05
Ok, I can reproduce now. It looks like an issue in `floaterm#wrapper#lf`. I get the same if I do e.g. `:exec 'FloatermNew nnn'` i.e. with the `nnn` wrapper from floaterm. I'll close this here, but please open an issue with https://github.com/voldikss/vim-floaterm.

**Closed as completed by ptzz** 2021-02-12 13:05 UTC
